# this is a program that will show you how much letters are there in your sentence or word.
take = input("Enter the word \ sentence ")
print(len(take) - take.count(' '))
print(take.count('a'))
print(take.count('b'))
print(take.count('c'))
print(take.count('d'))
print(take.count('e'))
print(take.count('f'))
print(take.count('g'))
print(take.count('h'))
print(take.count('i'))
print(take.count('j'))
print(take.count('k'))
print(take.count('l'))
print(take.count('m'))
print(take.count('n'))
