ask = input("Enter the first number")
ask2 = input("Enter the second number")
ask = int(ask)
ask2 = int(ask2)
print("the total is ", ask+ask2)
ask = input("Enter a float number")
ask2 = input("Enter another float number")
ask = float(ask)
ask2 = float(ask2)
print("Total of the numbers is ", ask + ask2)